apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicename }}
  labels:
    app: {{ .Values.servicelabel }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.serviceport }}
      targetPort: {{ .Values.containerport }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.podlabel }}
